version: "3.9"
services:
  actix-web-ldk:
    build: 
      context: ./backend/actix-web-ldk
      dockerfile: Dockerfile
    container_name: actix-web-ldk
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9732:9732"
    depends_on:
      - bitcoind
    networks:
      bridgednet:
        ipv4_address: 192.168.20.2

  bitcoind:
    container_name: bitcoind
    build: 
      context: ./backend/bitcoind
      dockerfile: Dockerfile
    ports:
      - "18443:18443"
      - "8333:8333"
      - "8332:8332"
      - "18333:18333"
      - "18332:18332"
      - "18444:18444"
    env_file:
      - ./backend/bitcoind/.env
    volumes:
      - ./backend/bitcoind/.bitcoin/bitcoin.conf:/home/bitcoin/volume/.bitcoin/bitcoin.conf
    networks:
      bridgednet:
        ipv4_address: 192.168.20.3

  nodejs:
    container_name: nodejs
    build: 
      context: ./backend/nodejs
      dockerfile: Dockerfile
    env_file:
      - ./backend/nodejs/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      bridgednet:
        ipv4_address: 192.168.20.4

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=userdb
    volumes:
      - ./backend/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongo-volume:/data/MONGO_INITDB_DATABASE
      - mongo_db:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      bridgednet:
        ipv4_address: 192.168.20.5

  react:
    container_name: react
    build: 
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      bridgednet:
        ipv4_address: 192.168.20.6

  postgres:
    image: postgres:14
    container_name: postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5243:5243"
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    networks:
      bridgednet:
        ipv4_address: 192.168.20.7

  nginx:
    container_name: nginx
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    networks:
      bridgednet:
        ipv4_address: 192.168.20.8

networks:
  bridgednet:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.20.0/24

volumes:
  mongo_db: {}
